trigger:
  branches:
    include:
    - master
parameters:
  - name: RESOURCE_GROUP
    displayName: Azure Resource Group
    type: string
    default: 'rg-dev-benefits-group'  
  - name: DMS_SERVICE_NAME
    displayName: DMS Service Name
    type: string
    default: 'lockton-dms-preprod'  
  - name: DMS_PROJECT_NAME
    displayName: DMS Project Name
    type: string
    default: 'vendorselect-dev'  
  - name: DMS_DATABASE_NAME
    displayName: DMS Database Name
    type: string
    default: 'Utility'  
  - name: RESOURCE_MANAGER_CONNECTION
    displayName: Azure Resource Connection Name
    type: string
    default: 'Central Services Dev Infrastructure'

stages:
#############################################################
# Build the code
# Currently this is not building and JAR files, but you would do that here
# This is packaging up the files from Git to the Artifacts files
#############################################################
- stage: DEV
  jobs:
  - job: JobDev
    displayName: 'Job Dev'
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: '${{ parameters.RESOURCE_MANAGER_CONNECTION }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az dms list
          az dms project list --resource-group '${{ parameters.RESOURCE_GROUP }}'' --service-name '${{ parameters.DMS_SERVICE_NAME }}'