trigger:
  branches:
    include:
    - master
parameters:
  - name: DMS_SERVICE_NAME  
    displayName: DMS Service Name
    type: string
    default: 'dms-benefits'  
  - name: DMS_PROJECT_NAME
    displayName: DMS Project Name
    type: string
    default: 'benefits-project'  
  - name: DMS_DATABASE_NAME
    displayName: DMS Database Name
    type: string
    default: 'All'  
  - name: RESOURCE_MANAGER_CONNECTION
    displayName: Azure Resource Connection Name
    type: string
    default: 'Central Services Dev Infrastructure'
  - name: SUBSCRIPTION_ID
    displayName: Azure subscription id
    type: string
    default: '5a3d1593-4191-401c-be7e-1aeb91c4c6f6'

stages:
#############################################################
# Build the code
# Currently this is not building and JAR files, but you would do that here
# This is packaging up the files from Git to the Artifacts files
#############################################################
- stage: DEV
  variables:
  - group: dms-benefits-dev
  - name: env
    value: dev
  - name: resource-group
    value: rg-$(env)-benefits-group
  - name: sku
    value: Standard_1vCores
  - name: vnet
    value: Dev-Infrastructure-SuperNets
  - name: vnet-resource-group
    value: RG-Dev-Infrastructure-VNet
  - name: subnet
    value: lockton-dms-subnet
  - name: full-vnet
    value: /subscriptions/${{ parameters.SUBSCRIPTION_ID }}/resourceGroups/$(vnet-resource-group)/providers/Microsoft.Network/virtualNetworks/$(vnet)/subnets/$(subnet)
  - name: service-name
    value: '${{ parameters.DMS_SERVICE_NAME }}-$(env)'
  - name: project-name
    value: '${{ parameters.DMS_PROJECT_NAME }}-$(env)'
  jobs:
  - job: JobDev
    displayName: 'Job Dev'
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: '${{ parameters.RESOURCE_MANAGER_CONNECTION }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az dms create -l centralus -n '$(service-name)' --resource-group '$(resource-group)' --sku-name '$(sku)' --subnet '$(full-vnet)'
          az dms list --resource-group '$(resource-group)'
          az dms project create -l centralus --service-name '$(service-name)' --resource-group '$(resource-group)' --project-name '$(project-name)' --source-platform SQL --target-platform SQLDB
          az dms project list --service-name '$(service-name)' --resource-group '$(resource-group)'
           