trigger:
  branches:
    include:
    - master
parameters:
  - name: RESOURCE_GROUP
    displayName: Azure Resource Group
    type: string
    default: 'rg-dev-benefits-group'  
  - name: DMS_SERVICE_NAME
    displayName: DMS Service Name
    type: string
    default: 'lockton-dms'  
  - name: DMS_PROJECT_NAME
    displayName: DMS Project Name
    type: string
    default: 'dms-benefits-dev'  
  - name: DMS_DATABASE_NAME
    displayName: DMS Database Name
    type: string
    default: 'All'  
  - name: RESOURCE_MANAGER_CONNECTION
    displayName: Azure Resource Connection Name
    type: string
    default: 'Central Services Dev Infrastructure'
  - name: SUBSCRIPTION_ID
    displayName: Azure subscription id
    type: string
    default: '5a3d1593-4191-401c-be7e-1aeb91c4c6f6'

stages:
#############################################################
# Build the code
# Currently this is not building and JAR files, but you would do that here
# This is packaging up the files from Git to the Artifacts files
#############################################################
- stage: DEV
  variables:
  - group: dms-benefits-dev
  - name: env
    value: dev
  - name: sku
    value: Standard_1vCores
  - name: vnet
    value: Dev-Infrastructure-SuperNets
  - name: subnet
    value: lockton-dms-subnet
  - name: full-vnet
    value: /subscriptions/${{ parameters.SUBSCRIPTION_ID }}/resourceGroups/${{ parameters.RESOURCE_GROUP }}/providers/Microsoft.Network/virtualNetworks
  - name: serviceName
    value: '${{ parameters.DMS_SERVICE_NAME }}-$(env)'
  - name: projectName
    value: '${{ parameters.DMS_PROJECT_NAME }}-$(env)'
  jobs:
  - job: JobDev
    displayName: 'Job Dev'
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: '${{ parameters.RESOURCE_MANAGER_CONNECTION }}'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az dms create -l centralus -n '${{ parameters.DMS_SERVICE_NAME }}-$(env)' --resource-group '${{ parameters.RESOURCE_GROUP }}' --sku-name '$(sku)' --subnet '$(full-vnet)'
           