trigger:
  branches:
    include:
    - master

stages:
#############################################################
# Build the code
# Currently this is not building and JAR files, but you would do that here
# This is packaging up the files from Git to the Artifacts files
#############################################################
- stage: DEV
  jobs:
  - job: JobDev
    displayName: 'Job Dev'
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: <Name of the Azure Resource Manager service connection>
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az account show
